### ISSUE TITLE
Module 4.1

### ISSUE THREAD

**Issue by arelia** [Campus-Advisors/campus-advisor-training-MrZebarth#14]
👋 Hi, you are missing the Module 4.1 Assignment. Please post your responses to the Education Community, then add a screenshot of your post here in this thread.

**Comment by MrZebarth** [comment]
Sorry! I posted the discussion, but forgot the screenshot!
![Module 4_1 Exercise](https://user-images.githubusercontent.com/5191364/93215349-466b0400-f734-11ea-8fa3-21eb70be8a95.png)
